version: '3.5'
services:
  db:
   image: "mysql:5.7"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USERNAME: root
     MYSQL_PASSWORD: root
   ports:
      - "3307:3306"
   volumes:
     - mysql-data:/var/lib/mysql
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.6.0
    ports:
      - "9200:9200"
    environment:
      "discovery.type": "single-node"
      "cluster.name": "elasticsearch-rails"
      "cluster.routing.allocation.disk.threshold_enabled": "false"
    depends_on:
      - db
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  redis:
   image: redis
   volumes:
      - redis:/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: bundle exec rails s -b '0.0.0.0' -p 5000
    volumes:
      - .:/myapp
    env_file:
      - .env
    depends_on:
      - db
      - elasticsearch
      - redis
    tty: true
    stdin_open: true
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/myapp
    env_file:
      - .env
    depends_on:
      - api
      - db
      - redis
    tty: true
    stdin_open: true
volumes:
  mysql-data:
  elasticsearch-data:
  redis:
